### ISSUE TITLE
Hey

### ISSUE THREAD

**Issue by SenseiKnatter** [DevFlash33/game#1]
Du bist Florian, richtig? Kennst mich noch? :D

**Comment by TrustNoOneElse** [comment]
Hey ja bin ich und ja kenne dich noch! :D Wie gehts? :D

**Comment by SenseiKnatter** [comment]
Mir geht es ganz gut :D. Mache seit August die Ausbildung zum FIAN... Hab einige Umwege gemacht :D. Fand es witzig unser altes game hier zu finden, war seit damals nie wieder eingeloggt :D

**Comment by TrustNoOneElse** [comment]
Das freut mich! :D Oh viel Erfolg! Finde beziehungsweise fand die Ausbildung mega ätzend :D Ja hast mir echt gut weitergeholfen, dadurch bringe ich Leuten jetzt sogar was bei :D

**Comment by DevFlash33** [comment]
Wenn du magst kannst du mir ja schreiben, flash3838@gmx.de :D Dann könnte man wieder die Nummern austauschen :D
